(() => {
  const atlas=document.querySelector('[data-component-atlas]'),systems=window.SFDesignSystems;
  if(!atlas||!systems)return;

  const safe=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const archetypeLabels={civic:'Civic hall',instrument:'Instrument bay',archive:'Evidence archive',poster:'Poster gallery',network:'Network chamber',gallery:'Quiet gallery',workshop:'Working studio',spatial:'Spatial chamber',field:'Field station',editorial:'Editorial room',desktop:'Desktop suite',playground:'Product playground',product:'Product gallery'};
  const COMPONENTS={
    actions:{label:'Actions',title:'Actions reveal a system’s attitude toward agency.',copy:'Compare prominence, physical feedback, label voice, disabled treatment, and the distance between ordinary and consequential actions.',prompts:['Which action wins the first glance?','Can pressed and disabled states be understood without color?','Does the language match the system’s voice?'],markup:'<div class="atlas-specimen-label">ACTIONS / ALL STATES</div><div class="lab-control-row"><button class="btn primary">Approve work</button><button class="btn">Review</button><button class="btn" disabled>Unavailable</button></div><a class="atlas-text-link" href="#">Read policy →</a>'},
    inputs:{label:'Inputs',title:'Inputs show how a system handles uncertainty and correction.',copy:'Hold the financial instruction constant and compare labeling, focus affordance, validation, error recovery, and the relationship between field and action.',prompts:['Is the label still visible after entry?','Does the error explain recovery?','Can focus survive the graphic language?'],markup:'<div class="atlas-specimen-label">BOUNDED INSTRUCTION</div><form class="lab-form" onsubmit="return false"><label>Maximum job budget <span>Required · USD</span><input value="$20.00"></label><label class="is-error">Destination <span>Needs review</span><input value="Unknown account" aria-invalid="true"><small>Choose an allowlisted account.</small></label></form>'},
    status:{label:'Status',title:'Status language exposes the system’s model of consequence.',copy:'Compare success, warning, and failure as a compact state family. Color is supplemental; wording and structure must carry the meaning.',prompts:['Can states be named without their colors?','Which state receives the strongest hierarchy?','Does urgency feel proportionate?'],markup:'<div class="atlas-specimen-label">SYSTEM FEEDBACK</div><div class="lab-alert success"><strong>Reconciled</strong><span>Ledger and rail agree.</span></div><div class="lab-alert warning"><strong>Reserve threshold</strong><span>Review before accepting work.</span></div><div class="lab-alert error"><strong>Payment blocked</strong><span>Destination is not allowed.</span></div>'},
    metrics:{label:'Metrics',title:'Metrics reveal what a system considers worth noticing.',copy:'The values, units, and qualifiers are identical. Study number scale, label hierarchy, density, and whether financial data feels stable enough to read.',prompts:['Are units subordinate but legible?','Do tabular figures feel native to the style?','Does one metric dominate for a reason?'],markup:'<div class="atlas-specimen-label">TREASURY SNAPSHOT / 14:32 UTC</div><div class="lab-kpis"><div><span>Available</span><strong>$12,480.22</strong><small>after obligations</small></div><div><span>Reserve</span><strong>64 days</strong><small>at current burn</small></div><div><span>Exceptions</span><strong>0</strong><small>close complete</small></div></div>'},
    table:{label:'Tables',title:'Tables test whether a style can survive operational truth.',copy:'Compare the same transaction ledger for scan order, row separation, numeric alignment, source context, and laptop-scale density.',prompts:['Can amounts be compared down the column?','Does status remain distinct from value?','Where do timestamp and provenance live?'],markup:'<div class="atlas-specimen-label">SETTLEMENT LEDGER / USD</div><div class="table-wrap atlas-table"><table><thead><tr><th>Job</th><th>Status</th><th>Net</th></tr></thead><tbody><tr><td>API audit</td><td>Cleared</td><td>+$42.80</td></tr><tr><td>Compute</td><td>Posted</td><td>−$6.20</td></tr><tr><td>Reserve</td><td>Held</td><td>$20.00</td></tr></tbody></table></div>'},
    navigation:{label:'Navigation',title:'Navigation turns brand hierarchy into spatial behavior.',copy:'Compare a compact product header with one active destination, utility status, and a clear return path. The specimen measures orientation rather than decoration.',prompts:['Is the active location unmistakable?','Does brand compete with navigation?','Can the system absorb more destinations?'],markup:'<div class="atlas-specimen-label">PRIMARY NAVIGATION</div><div class="atlas-mini-nav"><strong>SELF/FUNDING</strong><nav><a class="active" href="#">Overview</a><a href="#">Ledger</a><a href="#">Policy</a></nav><span>● Online</span></div><div class="atlas-mini-crumb">Home / Treasury / <b>Overview</b></div>'},
    cards:{label:'Cards',title:'Cards show whether grouping has a real logic.',copy:'The content stays constant while surface, spacing, metadata, and action placement change. Look for purposeful containment instead of habitual card chrome.',prompts:['Why does this content need a boundary?','Is metadata quieter without becoming faint?','Does the action belong inside the group?'],markup:'<article class="card atlas-product-card"><div class="metric-label">SERVICE / VERIFIED</div><h3>Dependency audit</h3><p>Inspect a software package for license, security, and maintenance risk.</p><div><span class="price">$18.00</span><a class="btn primary" href="#">Open report</a></div></article>'},
    chart:{label:'Charts',title:'Charts expose the difference between data language and decoration.',copy:'Seven fixed values test mark shape, axis discipline, signal color, annotation, and whether the graphic still works with a written summary.',prompts:['What variable does color encode?','Can the trend be understood without motion?','Is the written conclusion adjacent?'],markup:'<div class="atlas-specimen-label">SEVEN-DAY NET FLOW / USD</div><div class="lab-bars" aria-label="Net flow: 35, 52, 46, 70, 62, 84, 92"><i style="height:35%"></i><i style="height:52%"></i><i style="height:46%"></i><i style="height:70%"></i><i style="height:62%"></i><i style="height:84%"></i><i style="height:92%"></i></div><p class="atlas-chart-note">Net flow rose on five of seven days; latest value: $92.</p>'},
    tabs:{label:'Tabs',title:'Tabs test hierarchy inside a shared surface.',copy:'One active, two inactive, and one content panel reveal selection, hit area, label rhythm, and whether state remains clear across expressive systems.',prompts:['Is selection visible without relying on color?','Do labels feel like peers?','Does the panel belong to the active tab?'],markup:'<div class="atlas-specimen-label">ACCOUNT DETAIL</div><div class="lab-tabs" role="tablist"><button role="tab" aria-selected="true">Balance</button><button role="tab" aria-selected="false">Jobs</button><button role="tab" aria-selected="false">Audit</button></div><div class="lab-tab-panel">Available balance is spendable under current policy.</div>'},
    dialog:{label:'Dialogs',title:'Dialogs reveal how a system interrupts without disorienting.',copy:'A bounded approval prompt tests overlay hierarchy, consequence language, primary/secondary action distance, and the ability to return safely.',prompts:['Does the interruption explain why it occurred?','Is cancel genuinely available?','Can the user predict the result?'],markup:'<div class="atlas-dialog-static"><div class="atlas-dialog-title"><span>POLICY NOTICE</span><b>×</b></div><div class="atlas-dialog-body"><h3>Approve bounded work?</h3><p>This job may spend up to <strong>$2.40</strong>. No payout changes are permitted.</p><div class="lab-control-row"><button class="btn primary">Approve</button><button class="btn">Cancel</button></div></div></div>'}
  };

  const order=systems.order,themes=systems.themes,componentIds=Object.keys(COMPONENTS),params=new URLSearchParams(location.search),favoritesKey='systems38.atlas.favorites.v1';
  let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem(favoritesKey)||'[]').filter(id=>order.includes(id)));}catch(error){}
  const state={component:componentIds.includes(params.get('component'))?params.get('component'):'actions',q:params.get('q')||'',logic:params.get('logic')||'all',density:params.get('density')||'all',favorites:params.get('favorites')==='1'};
  const componentNav=atlas.querySelector('[data-atlas-components]'),grid=atlas.querySelector('[data-atlas-grid]'),search=atlas.querySelector('[data-atlas-search]'),logic=atlas.querySelector('[data-atlas-logic]'),density=atlas.querySelector('[data-atlas-density]'),favoriteToggle=atlas.querySelector('[data-atlas-favorites]'),empty=atlas.querySelector('[data-atlas-empty]'),status=atlas.querySelector('[data-atlas-status]');

  componentNav.innerHTML=componentIds.map((id,index)=>`<button type="button" data-atlas-component="${id}" aria-pressed="${state.component===id}"><span>${String(index+1).padStart(2,'0')}</span>${safe(COMPONENTS[id].label)}</button>`).join('');
  const addOptions=(select,values)=>[...new Set(values)].sort().forEach(value=>select.insertAdjacentHTML('beforeend',`<option value="${safe(value)}">${safe(value.charAt(0).toUpperCase()+value.slice(1))}</option>`));
  addOptions(logic,order.map(id=>themes[id].logic));addOptions(density,order.map(id=>themes[id].density));
  search.value=state.q;logic.value=[...logic.options].some(option=>option.value===state.logic)?state.logic:'all';density.value=[...density.options].some(option=>option.value===state.density)?state.density:'all';

  const specimenDocument=(id,component)=>`<!doctype html><html lang="en" data-theme="${id}" data-embed="true"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="shared/styles.css"></head><body class="atlas-specimen-body"><main class="atlas-specimen-stage">${COMPONENTS[component].markup}</main></body></html>`;
  const card=(id,index)=>{const theme=themes[id],curation=theme.curation,next=order[(index+1)%order.length],previous=order[(index-1+order.length)%order.length],favorite=favorites.has(id);return `<article class="atlas-card" data-atlas-card="${id}" data-logic="${safe(theme.logic)}" data-density="${safe(theme.density)}"><header><div><span>${String(index+1).padStart(2,'0')} / ${safe(archetypeLabels[curation.archetype])}</span><h3>${safe(theme.label)}</h3></div><button type="button" data-atlas-favorite="${id}" aria-pressed="${favorite}" aria-label="${favorite?'Remove':'Add'} ${safe(theme.label)} ${favorite?'from':'to'} favorites">${favorite?'★':'☆'}</button></header><div class="atlas-frame"><iframe loading="lazy" data-atlas-frame="${id}" title="${safe(theme.label)} ${safe(COMPONENTS[state.component].label)} specimen"></iframe></div><footer><p>${safe(curation.note)}</p><div><a href="system.html?theme=${id}">Enter room →</a><a href="compare.html?a=${id}&b=${next}&c=${previous}">Compare pages</a></div></footer></article>`;};
  grid.innerHTML=order.map(card).join('');

  const syncUrl=()=>{const url=new URL(location.href);for(const [key,value] of Object.entries(state)){if(key==='favorites'){if(value)url.searchParams.set(key,'1');else url.searchParams.delete(key);}else if(value&&value!=='all'&&(key!=='component'||value!=='actions'))url.searchParams.set(key,value);else url.searchParams.delete(key);}history.replaceState(null,'',url);};
  const updateFrames=()=>{for(const frame of atlas.querySelectorAll('[data-atlas-frame]')){frame.title=`${themes[frame.dataset.atlasFrame].label} ${COMPONENTS[state.component].label} specimen`;frame.srcdoc=specimenDocument(frame.dataset.atlasFrame,state.component);}};
  const renderGuide=()=>{const guide=COMPONENTS[state.component];atlas.querySelector('[data-atlas-current]').textContent=guide.label;atlas.querySelector('[data-atlas-guide-title]').textContent=guide.title;atlas.querySelector('[data-atlas-guide-copy]').textContent=guide.copy;atlas.querySelector('[data-atlas-prompts]').innerHTML=guide.prompts.map((prompt,index)=>`<div><span>${String(index+1).padStart(2,'0')}</span><p>${safe(prompt)}</p></div>`).join('');componentNav.querySelectorAll('[data-atlas-component]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.atlasComponent===state.component)));};
  const render=()=>{const query=state.q.trim().toLowerCase();let visible=0;for(const id of order){const theme=themes[id],curation=theme.curation,cardElement=grid.querySelector(`[data-atlas-card="${id}"]`),haystack=`${theme.label} ${theme.description} ${theme.logic} ${theme.density} ${archetypeLabels[curation.archetype]} ${curation.best} ${curation.headline}`.toLowerCase(),show=(!query||haystack.includes(query))&&(state.logic==='all'||theme.logic===state.logic)&&(state.density==='all'||theme.density===state.density)&&(!state.favorites||favorites.has(id));cardElement.hidden=!show;if(show)visible++;}atlas.querySelectorAll('[data-atlas-visible]').forEach(node=>node.textContent=visible);empty.hidden=visible!==0;status.textContent=visible===order.length?'All systems shown.':`Showing ${visible} of ${order.length} systems.`;favoriteToggle.setAttribute('aria-pressed',String(state.favorites));syncUrl();};

  componentNav.addEventListener('click',event=>{const button=event.target.closest('[data-atlas-component]');if(!button)return;state.component=button.dataset.atlasComponent;renderGuide();updateFrames();syncUrl();});
  search.addEventListener('input',()=>{state.q=search.value;render();});logic.addEventListener('change',()=>{state.logic=logic.value;render();});density.addEventListener('change',()=>{state.density=density.value;render();});favoriteToggle.addEventListener('click',()=>{state.favorites=!state.favorites;render();});
  atlas.addEventListener('click',event=>{const button=event.target.closest('[data-atlas-favorite]');if(!button)return;const id=button.dataset.atlasFavorite;if(favorites.has(id))favorites.delete(id);else favorites.add(id);try{localStorage.setItem(favoritesKey,JSON.stringify([...favorites]));}catch(error){}const active=favorites.has(id);button.textContent=active?'★':'☆';button.setAttribute('aria-pressed',String(active));button.setAttribute('aria-label',`${active?'Remove':'Add'} ${themes[id].label} ${active?'from':'to'} favorites`);if(state.favorites)render();});
  atlas.querySelectorAll('[data-atlas-reset]').forEach(button=>button.addEventListener('click',()=>{Object.assign(state,{component:'actions',q:'',logic:'all',density:'all',favorites:false});search.value='';logic.value=density.value='all';renderGuide();updateFrames();render();search.focus();}));
  atlas.querySelector('[data-atlas-copy-link]')?.addEventListener('click',async()=>{syncUrl();try{await navigator.clipboard.writeText(location.href);status.textContent='Shareable atlas link copied.';}catch(error){status.textContent='View URL is ready in the address bar.';}});

  renderGuide();updateFrames();render();
})();
